### ISSUE TITLE
`</head><body>`  tag in the wrong place

### ISSUE THREAD

**Issue by SukkaW** [curbengh/hexo-nofollow#5]
When I use `hexo-nofollow`, the `</head><body>` tag will be placed in a wrong position like this:

![image](https://user-images.githubusercontent.com/40715044/63209678-a862cf80-c116-11e9-8860-321ce48d37fa.png)

When I use an older version of `hexo-autonofollow`, the problem disappear, the `</head><body>` will be in the right place.

The issue might related to https://github.com/cheeriojs/cheerio/issues/1031 , and could be solved by adding `xmlMode: true` in the `cheerio.load` config to avoid this.

https://github.com/curbengh/hexo-nofollow/blob/b91feb8d32ed3980f734dbb19f2a0f9885109936/lib/filter.js#L43-L45

**Comment by curbengh** [comment]
My (rough) understanding is that `xmlMode` is only intended for dealing with XML file/content. It can cause unintended result when using with HTML.

For example in a code block of xml code, notice the undesired blank lines below the codes when I enable xmlMode,
![xmlmode-true](https://user-images.githubusercontent.com/43627182/63220972-33080500-c1d1-11e9-93f3-d52d613f96b5.png)

It's back to normal once I disable xmlMode,
![xmlmode-false](https://user-images.githubusercontent.com/43627182/63221056-2f28b280-c1d2-11e9-9d1b-a4d34f25be16.png)


I noticed that issue before, but couldn't reproduce reliably. Do you have sample repo that I can test?

You could also try the [v2.0 branch](https://github.com/curbengh/hexo-nofollow/tree/v2.0) which includes https://github.com/cheeriojs/dom-serializer/pull/85, but it's not directly related to the issue.
