### ISSUE TITLE
Deprecate hexo-nofollow

### ISSUE THREAD

**Issue by curbengh** [curbengh/hexo-nofollow#7]
@SukkaW
The [recent fix](https://github.com/curbengh/hexo-nofollow/pull/6) is created [by you](https://github.com/hexojs/hexo/pull/3685). Since you also have the [same plugin](https://github.com/SukkaW/hexo-filter-nofollow), I'm considering to deprecate this plugin in favor of yours.

The only difference between https://github.com/curbengh/hexo-nofollow/pull/6 and https://github.com/hexojs/hexo/pull/3685 is that I removed the following line:

```
if (/target=/gi.test(str)) return str;
```

because I prefer to have `rel=noopener...` regardless of existence of `target`.
If you can provide an option to disable that line, e.g.

```
if (/target=/gi.test(str) && !config.nofollow.ignoreTarget) return str;
```

then that would be nice. `config.nofollow.ignoreTarget` can be disabled by default.

**Comment by SukkaW** [comment]
In fact I have deprecated hexo-filter-nofollow and ask users to use hexo-nofollow..
Maybe I can add you to the package maintainer.

**Comment by SukkaW** [comment]
```bash
$ npm owner add curben hexo-filter-nofollow
+ curben (hexo-filter-nofollow)
```

Done.

**Comment by curbengh** [comment]
I'll create PRs to https://github.com/SukkaW/hexo-filter-nofollow.
In the meantime, can you enable "Issues" in your repo?

**Comment by curbengh** [comment]
This is a bit tricky due to [github limitation](https://stackoverflow.com/questions/6675994/is-it-possible-to-fork-a-fork-in-github) on forking a fork.

**Comment by SukkaW** [comment]
I am thinking to create a new `hexo-filter-nofollow` repo under hexo organization.

**Comment by curbengh** [comment]
In the meantime, let's update your repo.
https://github.com/SukkaW/hexo-filter-nofollow/pull/1

**Comment by SukkaW** [comment]
I think it is a good idea to create a new repo `hexo-filter-nofollow` under hexo organization, and then push `hexo-nofollow` into that repo.

**Comment by curbengh** [comment]
hexo-nofollow already falls behind hexo-filter-nofollow. I prefer not to duplicate the commits of [current PRs](https://github.com/SukkaW/hexo-filter-nofollow/pulls) of hexo-filter-nofollow.

Do you still intend to keep the repo under yourself? Otherwise, why not just migrate (transfer ownership) it to hexo.

**Comment by SukkaW** [comment]
After migrate the current `hexo-filter-nofollow` repo into hexo organization still have the problem of `fork a forked repo`.
Also, I want to rewrite this plugin completely.

**Comment by curbengh** [comment]
So, you're not proceeding with https://github.com/orgs/hexojs/teams/core/discussions/9?

I'm holding off deprecation for now, until your rewrite. Depending how drastic is the change, I may or may not deprecate this plugin.
